version: '3'
services:
    dbos:
       image: mariadb
       volumes:
             - mysql_storage:/var/lib/mysql
       restart: always
       environment:
                MYSQL_ROOT_PASSWORD: rootpass
                MYSQL_USER: anisha
                MYSQL_PASSWORD: redhat
                MYSQL_DATABASE: mydbs
    nextcloud:
        image: nextcloud
        restart: always
        ports:
            - 8081:80
        links:
            - dbos
        volumes:
            - nextcloud_stg:/var/www/html
volumes:
      - mysql_storage:
      - nextcloud_std:/var/www/html
